### ISSUE TITLE
Enum field input should be a select

### ISSUE THREAD

**Issue by jordanmaguire** [thefrontiergroup/frontier_generators#159]
Example:

In model:

``` ruby
enum point_type: {activity: 0, cow: 1, offer: 2, photo_opportunity: 3, site: 4, standard: 5}
```

In view:

``` haml
= f.input :point_type, collection: PointOfInterest.point_types.keys.map {|value| [I18n.t(value, scope: [:point_of_interest, :point_types]), value]}
```

In specs...

``` ruby
select(I18n.t(point_of_interest_attributes[:point_type], scope: [:point_of_interest, :point_types]), from: "Point type")
```

in en.yml

``` yaml
en:
  point_of_interest:
    point_types:
      activity: "Activity"
      cow: "Cow"
      offer: "Offer"
      photo_opportunity: "Photo Opportunity"
      site: "Site"
      standard: "Standard"
```
