### ISSUE TITLE
Enum: index should show humanized value

### ISSUE THREAD

**Issue by jordanmaguire** [thefrontiergroup/frontier_generators#160]
Example:

In model:

``` ruby
enum point_type: {activity: 0, cow: 1, offer: 2, photo_opportunity: 3, site: 4, standard: 5}
```

in en.yml

``` yaml
en:
  point_of_interest:
    point_types:
      activity: "Activity"
      cow: "Cow"
      offer: "Offer"
      photo_opportunity: "Photo Opportunity"
      site: "Site"
      standard: "Standard"
```

On index

``` haml
%td= I18n.t(point_of_interest.point_type, scope: [:point_of_interest, :point_types])
```
