### ISSUE TITLE
Add support for belongs_to as inline form

### ISSUE THREAD

**Issue by jordanmaguire** [thefrontiergroup/frontier_generators#4]
See: El Mulcho

**Comment by jordanmaguire** [comment]
```yaml
attributes:
  billing_address:
    # Possibly?
    load_from_yaml: /path/to/yaml
    nested_attributes: [line_1, line_2, city, state]
    # Default: billing_address_fields
    partial_name: address_fields
    type: belongs_to
```
