### ISSUE TITLE
Migrations for attributes with different class names are broken

### ISSUE THREAD

**Issue by Ruxton** [thefrontiergroup/frontier_generators#80]
```
interview_questionnaire:
  namespaces: ["member"]
  skip_seeds: true
  attributes:
    gp_address:
      show_on_index: false
      type: belongs_to
      class_name: "Address"
```

will generate the following migration

```
class CreateInterviewQuestionnaire < ActiveRecord::Migration
  def change
    create_table :interview_questionnaires do |t|
      t.belongs_to :gp_address, index: true, foreign_key: true
      t.datetime :created_at
      t.datetime :updated_at
      t.datetime :deleted_at
    end
    add_index :interview_questionnaires, :deleted_at
  end
end
```

This will fail ```PGError: ERROR: relation “gp_address” does not exist```.  The migration requires a 'references' component, which you can't use foreign_key: true on :/.  Migration should end up looking like this for it to work.

```
class CreateInterviewQuestionnaire < ActiveRecord::Migration
  def change
    create_table :interview_questionnaires do |t|
      t.belongs_to :gp_address, references: :addresses, index: true
      t.datetime :created_at
      t.datetime :updated_at
      t.datetime :deleted_at
    end
    add_index :interview_questionnaires, :deleted_at
    add_foreign_key :interview_questionnaires, :addresses, column: :gp_address_id
  end
end
```
