### ISSUE TITLE
Form generation for associations is broken.

### ISSUE THREAD

**Issue by Ruxton** [thefrontiergroup/frontier_generators#81]
```
interview_questionnaire:
  namespaces: ["member"]
  skip_seeds: true
  attributes:
    address:
      show_on_index: false
      type: belongs_to
```

generates..

```
= simple_form_for [:member, @interview_questionnaire], wrapper: "horizontal", html: {class: "form-horizontal"} do |f|
  = f.association :address_id, collection: Address.all
  .form-actions
    = f.button :submit
    %span.or or
    = link_to "Cancel", member_interview_questionnaires_path
```

instead of 

```
= simple_form_for [:member, @interview_questionnaire], wrapper: "horizontal", html: {class: "form-horizontal"} do |f|
  = f.association :address, collection: Address.all
  .form-actions
    = f.button :submit
    %span.or or
    = link_to "Cancel", member_interview_questionnaires_path
```
