### ISSUE TITLE
extra comma on belongs_to association

### ISSUE THREAD

**Issue by osiro** [thefrontiergroup/frontier_generators#9]
The following yaml:

```yaml
address:
  attributes:
    line_1:
      type: "string"
      validates:
        presence: true
    line_2:
      type: "string"
    suburb:
      type: "string"
      validates:
        presence: true
    postal_code:
      type: "string"
      validates:
        presence: true
    state:
      type: "belongs_to"
      validates:
        presence: true
```

Generated:

```ruby
class Address < ActiveRecord::Base
  # Soft delete - uses deleted_at field
  acts_as_paranoid

  belongs_to :state,

  validates :line_1, presence: true
  validates :suburb, presence: true
  validates :postal_code, presence: true
  validates :state, presence: true

  def to_s
    line_1
  end

end
```

Didn't have enough time to look into that, but I think it's something to do in here: https://github.com/thefrontiergroup/frontier_generators/blob/master/lib/model_configuration/association.rb#L40

BTW, in newer versions of Rails, we do not need to do `validates :state, presence: true`, we can pretty much do `belongs_to :state, required: true`.

Thought about changing the generators to validates associations with require true.
